name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - test

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install && npx prisma generate

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Compose
        uses: docker/setup-qemu-action@v2

      - name: Ensure Docker Compose is available
        run: docker compose version

      - name: Copy .env.example to .env
        run: cp .env.example .env

      - name: Grant execute permissions to wait-for-it.sh
        run: chmod +x ./scripts/wait-for-it.sh

      - name: Grant execute permissions to run-integration.sh
        run: chmod +x ./scripts/run-integration.sh

      - name: Run integration script
        run: npm run test:integration
